Settings:
  chatFormat: "%color%chatPrefix%nick %donate -> %message"
  messageHover:
    - "%player_name%"
    - "%player_exp%"

Database:
  log: true # Будут ли логироватся сообщения?
  type: postgresql
  host: 217.171.146.202
  port: 5432
  name: server_prod
  user: elmo
  pass: ElmoDev

Permissions:
  bypassAdd: "e1ch.admin"
  bypassWord: "e1ch.admin"

AntiAdd:
  enable: true
  BlockList: # | Если, что-то из этого списка будет в сообщении игрока - сообщение не будет отправлено.
    - "https"
    - ".com"
    - ".ru"

AntiWords:
  enable: true
  BlockList:
    - "E1m0" # Например: Ник основателя сервера и администрации, чтобы не было упоминаний о нем для сокрытия высшей администрации.

Messages:
  Errors:
    cooldownDown: "У вас осталось еще %sec до конца задержки!"
    notAFindChat: "Не найдено не одного чата"
    blockWord: "Это слово - запрещено!"
    blockAdd: "Подозрения на рекламу!"

Effects:
  Mention:
    message: "Вас упомянули в чате! %sender!"
    sound: "ENTITY_PLAYER_LEVELUP"

AutoMessage:
  enable: true
  cooldown: 10
  Broadcast:
    message:
    - "--"
    - "&c! | &7Если перед ник неймом поставить @Dev то получатель получит извещение о упоминании!"
    - "--"
  Dev:
    message:
      - "--"
      - "&7&#FD9B1AН&#FC9A1Bа&#FB991Cв&#F9971Dе&#F8961Eд&#F7951Fи&#F69420т&#F59321е &#F29023н&#F18F24а &#EF8D26с&#EE8C27о&#EC8A28о&#EB8929б&#EA8829щ&#E9872Aе&#E8862Bн&#E7852Cи&#E5832Dе &#E3812Fи&#E28030г&#E17F31р&#DF7D32о&#DE7C33к&#DD7B34а &#DB7936ч&#DA7837т&#D87638о&#D77539б&#D6743Aы &#D4723Cп&#D2703Dо&#D16F3Eс&#D06E3Fм&#CF6D40о&#CE6C41т&#CC6A42р&#CB6943е&#CA6844т&#C96745ь &#C76546е&#C56347г&#C46248о &#C2604Aс&#C15F4Bт&#BF5D4Cа&#BE5C4Dт&#BD5B4Eи&#BC5A4Fс&#BB5950т&#BA5851и&#B85652к&#B75553у&#B65454!"
      - "--"
  Elmo:
    message:
      - "--"
      - "<gradient:#FD1AEE:#8154B6>E1m0dev</gradient>"
      - "--"

Chats:
  Global:
    permission: "e1ch.player"
    cooldown: 3 # Сколько еще нельзя будет писать в этот чат?
    prefix: "G | "
    radius: 0
    color: "&7"
    tag: "!"
  Local:
    permission: "e1ch.player"
    cooldown: 3
    prefix: "L | "
    radius: 7
    color: "&7"
    tag: ""
  Dev:
    permission: "e1ch.player"
    cooldown: 0
    prefix: "D | "
    radius: 0
    color: ""
    tag: "$"
  Admin:
    permission: "e1ch.adm"
    cooldown: 5
    prefix: "Admin | "
    radius: 0
    color: "&c"
    tag: "*"